name: Reproduce Hydra Build

on:
  workflow_dispatch:
    inputs:
      build_id:
        description: 'Hydra Build ID'
        required: true
        default: '331551869'

jobs:
  reproduce:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Free disk space
        run: |
          sudo rm -rf /usr/share/dotnet
          sudo rm -rf /usr/local/lib/android
          sudo rm -rf /opt/ghc
          sudo rm -rf /opt/hostedtoolcache

      - name: Install Nix
        uses: cachix/install-nix-action@v31
        with:
          github_access_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Reproduce Build
        run: curl -sSfL "https://hydra.nixos.org/build/${{ github.event.inputs.build_id }}/reproduce" | bash
